package vendingmachine.ui;

import java.awt.Graphics;
import java.awt.image.BufferedImage;

import javax.swing.JPanel;

// inspired by a solution found on the 22-11-2015 on 
// https://wikigurus.com/Article/Show/56465/How-to-set-an-image-as-a-background-for-Frame-in-Swing-GUI-of-java
public class BackgroundJPanel extends JPanel {

  private static final long serialVersionUID = 1L; // generated by Eclipse
  private final BufferedImage background;

  public BackgroundJPanel(BufferedImage background) {
    super();
    this.background = background;
  }

  @Override
  public void paintComponent(Graphics g) {
    super.paintComponent(g);
    g.drawImage(background, 0, 0, getWidth(), getHeight(), null);
  }

}