package vendingmachine.ui;

import javax.swing.BorderFactory;
import javax.swing.JButton;

import vendingmachine.components.Coin;

/**
 * The CoinJButton class extends JButton and only adds a Coin attribute.
 * 
 * @see Coin
 */
public class CoinJButton extends JButton {

  private static final long serialVersionUID = 1L; // generated by Eclipse
  
  private final Coin coin;

  /**
   * Creates a JButton that has a Coin as a attribute.
   * Sets the ICON attribute of the Coin as icon if it loaded properly.
   * If the ICON attribute is null, then only sets the TEXT on the button.
   * 
   * @param coin The coin linked with the button
   */
  public CoinJButton(Coin coin) {
    super();
    if (coin.ICON != null) {
      this.setIcon(coin.ICON);
      setBorder(BorderFactory.createEmptyBorder());
      setContentAreaFilled(false);
    } else { 
      this.setText(coin.TEXT);
    }
    this.coin = coin;
  }

  /**
   * @return the Coin associated with the CoinJButton.
   */
  public Coin getCoin() {
    return this.coin;
  }

}