package vendingmachine.ui;

import javax.swing.BorderFactory;
import javax.swing.JButton;

import vendingmachine.Coin;
import vendingmachine.PictureLoader;

/**
 * The CoinJButton class extends JButton and only adds a Coin attribute.
 * 
 * @see Coin
 */
public class CoinJButton extends JButton {

  private static final long serialVersionUID = 1L; // generated by Eclipse

  /**
   * The Coin associated with the JButton.
   */
  private final Coin coin;

  /**
   * Creates a JButton that has a Coin as a attribute.
   * Sets the ImageIcon gotten in COINS_IMAGES of PictureLoader.
   * If the image is null, simply sets the Coin.TEXT on the button.
   * 
   * @param coin the coin linked with the button
   */
  public CoinJButton(Coin coin) {
    super();
    final PictureLoader icons = PictureLoader.getInstance();
    if (icons.COINS_IMAGES.get(coin) != null) {
      this.setIcon(icons.COINS_IMAGES.get(coin));
      this.setBorder(BorderFactory.createEmptyBorder());
      this.setContentAreaFilled(false);
    } else {
      this.setText(coin.TEXT);
    }
    this.coin = coin;
  }

  /**
   * @return the Coin associated with the CoinJButton.
   */
  public Coin getCoin() {
    return this.coin;
  }

}