package vendingmachine.ui;

import javax.swing.*;

import vendingmachine.PictureLoader;
import vendingmachine.components.Drink;

public class DrinkJButton extends JButton {

	private static final long serialVersionUID = 1L; //generated by Eclipse
	private Drink drink;

	public DrinkJButton(Drink drink) {
		super();
		this.drink = drink;
		setText(drink.getName());
		setIcon(new ImageIcon(PictureLoader.drinkButton));
		setBorder(BorderFactory.createEmptyBorder());
		setContentAreaFilled(false);
		setHorizontalTextPosition(JButton.CENTER);
		setVerticalTextPosition(JButton.CENTER);
	}

	public Drink getDrink() {
		return this.drink;
	}

}