package vendingmachine.ui;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.SwingConstants;

import vendingmachine.Drink;
import vendingmachine.PictureLoader;

/**
 * The DrinkJButton class extends JButton and only adds a Drink attribute.
 */
public class DrinkJButton extends JButton {

  private static final long serialVersionUID = 1L; // generated by Eclipse
  
  /**
   * The drink associated with the JButton.
   */
  private final Drink drink;

  /**
   * Associates a JButton with the Drink specified.
   * Sets the name of the drink and the icon of a button (if it loaded properly).
   * 
   * @param drink the Drink to associate with the JButton
   */
  public DrinkJButton(Drink drink) {
    super();
    this.drink = drink;
    this.setText(drink.getName());
    PictureLoader pictures = PictureLoader.getInstance();
    if (pictures.DRINK_BUTTON != null) {
      this.setIcon(pictures.DRINK_BUTTON);
      this.setBorder(BorderFactory.createEmptyBorder());
      this.setContentAreaFilled(false);
      this.setHorizontalTextPosition(SwingConstants.CENTER);
    }
  }

  /**
   * @return the Drink associated with the DrinkJButton
   */
  public Drink getDrink() {
    return this.drink;
  }

}